#!/usr/bin/env python3
import sys
import os

paths = {
    "color": "/sys/class/leds/system76_acpi::kbd_backlight/color",
    "brightness": "/sys/class/leds/system76_acpi::kbd_backlight/brightness"
}

if len(sys.argv) == 3 and sys.argv[1] in paths:
    with open(paths[sys.argv[1]], "w") as f:
        f.write(sys.argv[2])
        f.flush()
        os.fsync(f.fileno())
